// <auto-generated />
using System;
using BoilerPlate.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoilerPlate.Persistence.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoilerPlate.Domain.Entities.Faq.FaqContent", b =>
                {
                    b.Property<Guid>("FqContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedByDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedByDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FaqHeadFqHeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FqContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FqHeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FqTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastUpdatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastUpdatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDtServer")
                        .HasColumnType("datetime2");

                    b.HasKey("FqContentId");

                    b.HasIndex("CreatedDt");

                    b.HasIndex("CreatedDtServer");

                    b.HasIndex("DeletedByDt");

                    b.HasIndex("FaqHeadFqHeadId");

                    b.HasIndex("FqHeadId");

                    b.HasIndex("FqTitle");

                    b.HasIndex("LastUpdatedDt");

                    b.HasIndex("LastUpdatedDtServer");

                    b.ToTable("FaqContent");
                });

            modelBuilder.Entity("BoilerPlate.Domain.Entities.Faq.FaqHead", b =>
                {
                    b.Property<Guid>("FqHeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedByDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedByDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FqActiveContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastUpdatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastUpdatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDtServer")
                        .HasColumnType("datetime2");

                    b.HasKey("FqHeadId");

                    b.HasIndex("CreatedDt");

                    b.HasIndex("CreatedDtServer");

                    b.HasIndex("DeletedByDt");

                    b.HasIndex("FqActiveContentId");

                    b.HasIndex("FqHeadId");

                    b.HasIndex("LastUpdatedDt");

                    b.HasIndex("LastUpdatedDtServer");

                    b.ToTable("FaqHead");
                });

            modelBuilder.Entity("BoilerPlate.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("CountryCode")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedByDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedByDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EmailActivationAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailActivationCode")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("EmailActivationStatus")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastPasswordChangeAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastUpdatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastUpdatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserState")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedDt");

                    b.HasIndex("CreatedDtServer");

                    b.HasIndex("DeletedByDt");

                    b.HasIndex("FullName");

                    b.HasIndex("LastUpdatedDt");

                    b.HasIndex("LastUpdatedDtServer");

                    b.HasIndex("NormalizedUsername");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BoilerPlate.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedByDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedByDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastUpdatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastUpdatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDtServer")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("CreatedDt");

                    b.HasIndex("CreatedDtServer");

                    b.HasIndex("DeletedByDt");

                    b.HasIndex("LastUpdatedDt");

                    b.HasIndex("LastUpdatedDtServer");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("BoilerPlate.Domain.Entities.UserRoleLog", b =>
                {
                    b.Property<Guid>("UserRoleLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedByDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedByDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastUpdatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastUpdatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDtServer")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRoleLogId");

                    b.HasIndex("CreatedDt");

                    b.HasIndex("CreatedDtServer");

                    b.HasIndex("DeletedByDt");

                    b.HasIndex("LastUpdatedDt");

                    b.HasIndex("LastUpdatedDtServer");

                    b.ToTable("UserRoleLog");
                });

            modelBuilder.Entity("BoilerPlate.Domain.Entities.UserToken", b =>
                {
                    b.Property<Guid>("UserTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedByDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedByDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastUpdatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastUpdatedDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDtServer")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserTokenId");

                    b.HasIndex("CreatedDt");

                    b.HasIndex("CreatedDtServer");

                    b.HasIndex("DeletedByDt");

                    b.HasIndex("LastUpdatedDt");

                    b.HasIndex("LastUpdatedDtServer");

                    b.HasIndex("UserId");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("BoilerPlate.Domain.Entities.Faq.FaqContent", b =>
                {
                    b.HasOne("BoilerPlate.Domain.Entities.Faq.FaqHead", "FaqHead")
                        .WithMany("FaqContent")
                        .HasForeignKey("FaqHeadFqHeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaqHead");
                });

            modelBuilder.Entity("BoilerPlate.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("BoilerPlate.Domain.Entities.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BoilerPlate.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("BoilerPlate.Domain.Entities.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BoilerPlate.Domain.Entities.Faq.FaqHead", b =>
                {
                    b.Navigation("FaqContent");
                });

            modelBuilder.Entity("BoilerPlate.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
